version: "1"
services:
  web:
    stdin_open: true
    tty: true
    build: client/my-app
    volumes:
      - './client/my-app:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_NAME=my-app
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    image: mongo
    ports:
      - 3333:3333
    volumes:
      - ./db:/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  laravel_default:
      driver: bridge