version: "1"
services:
  web:
    stdin_open: true
    tty: true
    build: client/my-app
    volumes:
      - './client/my-app:/app'
      - '/app/node_modules'
      - './client/my-app/package.json:/app/package.json'
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_NAME=my-app
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:8
    container_name: db
    ports:
      - '3308:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel_default
  php:
    build:
      dockerfile: php/Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/laravel_docker
      - ./src/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8080:80
networks:
  laravel_default:
      driver: bridge